import '../styles/globals.css'

import NavBar from "../components/NavBar";
import SideBar from "../components/SideBar";
import { NavBarIcon } from '../components/MenuIcons';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <NavBar>
        <NavBarIcon text="Home" to={'/'}></NavBarIcon>
        <NavBarIcon text="Tools" to={undefined}></NavBarIcon></NavBar>
      <SideBar />
      <body>{children}</body>
    </>
  )
}
