import "../styles/globals.css";

import React from "react";

import NavBar from "../components/NavBar";
import SideBar from "../components/SideBar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <div className="page">{children}</div>
      </body>
    </html>
  );
}
